#!/bin/sh

# chkconfig: 2345 99 01
# description: Bricolage CMS

# Created by David Wheeler, 2005.

# This is an example of a start/stop script for SysV-style init, such as is
# used on Linux systems. You should these variables:

BRICOLAGE_ROOT="/usr/local/bricolage"
BRIC_APACHECTL="$BRICOLAGE_ROOT/bin/bric_apachectl"
USE_BRIC_QUEUED=0
DIST_USERNAME=
DIST_PASSWORD=
DIST_INTERVAL=30
BRIC_QUEUED=$BRICOLAGE_ROOT/bin/bric_queued
DIST_PIDFILE=$BRICOLAGE_ROOT/log/bric_queued.pid
DIST_LOG=$BRICOLAGE_ROOT/log/bric_queued.log

# Then just copy it to your start scripts directory (usually /etc/init.d) and
# add it to the startup process:

# % cp contrib/start_scripts/linux /etc/init.d/bricolage
# % chmod +x /etc/init.d/bricolage
#
# Then, either create symlinks to the startup script:
#
# % ln -s /etc/init.d/bricolage /etc/rc.d/rc0.d/K02bricolage
# % ln -s /etc/init.d/bricolage /etc/rc.d/rc1.d/K02bricolage
# % ln -s /etc/init.d/bricolage /etc/rc.d/rc2.d/K02bricolage
# % ln -s /etc/init.d/bricolage /etc/rc.d/rc3.d/S98bricolage
# % ln -s /etc/init.d/bricolage /etc/rc.d/rc4.d/S98bricolage
# % ln -s /etc/init.d/bricolage /etc/rc.d/rc5.d/S98bricolage
#
# Or, if you have chkconfig, simply:
#
# % /sbin/chkconfig --add bricolage

##############################################################################

$BRIC_APACHECTL "$@"

if [ $USE_BRIC_QUEUED ]; then
    case "$1" in
        start)
            "$BRIC_QUEUED" --username "$DIST_USERNAME" \
                --password "$DIST_PASSWORD" \
                --log "$DIST_LOG" \
                --pid "$DIST_PIDFILE" --delay "$DIST_INTERVAL"
            echo bric_queued: started
            ;;
        stop)
            if [ -f "$DIST_PIDFILE" ]; then
                kill `cat "$DIST_PIDFILE"`
                echo bric_queued: stopped
            fi
            ;;
        restart)
            if [ -f "$DIST_PIDFILE" ]; then
                kill `cat "$DIST_PIDFILE"`
            fi
            "$BRIC_QUEUED" --username "$DIST_USERNAME" \
                --password "$DIST_PASSWORD" \
                --log "$DIST_LOG" \
                --pid "$DIST_PIDFILE" --delay "$DIST_INTERVAL"
            echo bric_queued: restarted
            ;;
    esac;
fi
