=head1 NAME

Bric::Changes - Bricolage Changes

=head1 VERSION

$Revision$

=head1 DATE

$Date$

=head1 DESCRIPTION

This document lists the Changes to Bricolage introduced with each release.

=head1 VERSION 1.2.0

=head2 New Features

=over 4

=item *

Added Context-sensitive, online help. [Sam]

=item *

Added separate interface for editing templates (via FTP). [Sam]

=item *

Added the ability to use HTML::Template Templates. [Sam]

=back

=over 4

=item *

Fixed a bug with local previews where a preview page could show up instead of
the Bricoalge UI. Thanks to Sara for the spot. [David]

=item *

Fixed a bug where Mason component calls failed in previews when the
PREVIEW_MASON directive was enabled. [David]

=back

=head1 VERSION 1.0.2

=over 4

=item *

Added "File Name" and "File Extension" properties to OutputChannels. These
properties will now be used to name files burned to the file system on
preview and publish. [David]

=item *

Added DEFAULT_FILENAME and DEFAULT_FILE_EXT configuration directives to set
default values on the "File Name" and "File Extenstion" Output Channel
properties. [David]

=item *

Changed Bric::Util::Burner->display_element() so that it doesn't paginate. All
paginated pages are now treated instead as regular elements. This is useful for
things like printer-freindly pages. Bric::Util::Burner->display_element()
contines to work as before. Use this method to output a separate file for each
paginated element. [David]

=item *

When errors occur while previewing stories, the leftNav is now turned off.
[David]

=item *

Browser buttons and menus are now disabled for all browsers except IE. Fixes to
get IE to leave them out, too, are welcome. [David]

=item *

Added ability to set permissions on assets based on the categories they're in.
[David]

=item *

Moved all session and session locking files into the "bricolage" subdirectory fo
the local file system's tmp directory. You'll want to rm -rf /tmp/bricolage_*.

=item *

Moved the location of cache files to the "bricolage/cache" subdirectory of the
local file system's tmp directory. You'll want to rm -rf /tmp/FileCache.
Together with the above change, this means that all Bricolage temporary files
are stored in the "bricolage" subdirectory of the local tmp, e.g.,
/tmp/bricolage.

=item *

Fixed bug where cancelled checkouts of template appeared to work in some views,
but not others. Thanks to Matt Vella for the report. [David]

=item *

Fixed bug where story titles were accentally getting bogus hyperlinking markup.
Thanks to Chris Brody for the report. [David]

=item *

Fixed a bug where the "Generic" check box on the "New Template" screen was
partially ignored, leading to possibly corrupted data, and at least to the
inability to create autohandlers. Thanks to Sam Tregar for the bug report that
led to finding this bug. [David]

=item *

Fixed bug where element checkboxes weren't remembering if they were checked or
not. Thanks to Matt Vella for the spot. [David]

=back

=head1 VERSION 1.0.1

=over 4

=item *

Initial public release.

=back

=head1 VERSION 1.2.0

=item *

Added context-sensitive online help.

=item *

Added separate interface for editing templates via FTP.

=item *

Added support for HTML::Template.

=head1 AUTHOR

David Wheeler <david@wheeler.net>

=head1 SEE ALSO

perl(1),
Bric (2).

=cut
