=head1 NAME

Bric::Changes - Bricolage Changes

=head1 VERSION

$Revision$

=head1 DATE

$Date$

=head1 DESCRIPTION

This document lists the Changes to Bricolage introduced with each release.

=head1 VERSION 1.0.2

=head2 New Features

=over 4

=item *

Added "File Name" and "File Extension" properties to OutputChannels. These
properties will now be used to name files burned to the file system on
preview and publish. [David]

=item *

Added DEFAULT_FILENAME and DEFAULT_FILE_EXT configuration directives to set
default values on the "File Name" and "File Extenstion" Output Channel
properties. [David]

=item *

Changed Bric::Util::Burner->display_element() so that it doesn't paginate. All
paginated pages are now treated instead as regular elements. This is useful for
things like printer-freindly pages. Bric::Util::Burner->display_element()
contines to work as before. Use this method to output a separate file for each
paginated element. [David]

=item *

When errors occur while previewing stories, the leftNav is now turned off.
[David]

=item *

Browser buttons and menus are now disabled for all browsers except IE. Fixes to
get IE to leave them out, too, are welcome. [David]

=item *

Added ability to set permissions on assets based on the categories they're in.
[David]

=item *

Moved all session and session locking files into the "bricolage" subdirectory fo
the local file system's tmp directory. You'll want to rm -rf /tmp/bricolage_*.

=item *

Moved the location of cache files to the "bricolage/cache" subdirectory of the
local file system's tmp directory. You'll want to rm -rf /tmp/FileCache.
Together with the above change, this means that all Bricolage temporary files
are stored in the "bricolage" subdirectory of the local tmp, e.g.,
/tmp/bricolage.

=item *

Added an "About" page, linked from the logo graphic, that explains the name
"Bricolage" and offers the license and credits. [David]

=item *

Added PERL_LOADER configuration directive. Pass a line of Perl to this
directive, and on startup, it'll execute it in the same namespace as your
templates execute in.

=item *

Added INCLUDE_XML_WRITER and XML_WRITER_ARGS configuration parameters. If
INCLUDE_XML_WRITER is turned on, then all templates will include a new global,
$writer, that is an XML::Writer object. This object is provided as a convenience
for creating XML in your templates. XML_WRITER_ARGS allows certain arguments to
be passed to the XML::Writer instantiator. See Bric::AdvTemplates for more
information.

=item *

Added URI information to associated categories in the story profile. [David]

=item *

Changed category selection for new Templates to use the category URI rather than
the name, in line with how Story and Media work. [David]

=back

=head2 Bug Fixes

=over 4

=item *

Fixed bug where cancelled checkouts of template appeared to work in some views,
but not others. Thanks to Matt Vella for the report. [David]

=item *

Fixed bug where story titles were accentally getting bogus hyperlinking markup.
Thanks to Chris Brody for the report. [David]

=item *

Fixed a bug where the "Generic" check box on the "New Template" screen was
partially ignored, leading to possibly corrupted data, and at least to the
inability to create autohandlers. Thanks to Sam Tregar for the bug report that
led to finding this bug. [David]

=item *

Fixed bug where element checkboxes weren't remembering if they were checked or
not. Thanks to Matt Vella for the spot. [David]

=item *

Fixed bug where element select lists weren't populate with their list of values.
Thanks to Matt Vella for the report. [David]

=item *

Fixed select lists and radio buttons in formBuilder so that they can take just
values as well as value/name pairs. [David]

=back

=head1 VERSION 1.0.1

=over 4

=item *

Initial public release.

=back

=head1 AUTHOR

David Wheeler <david@wheeler.net>

=head1 SEE ALSO

perl(1),
Bric (2).

=cut
