=head1 NAME

Bric::Changes - Bricolage Changes

=head1 VERSION

$Revision$

=head1 DATE

$Date$

=head1 DESCRIPTION

This document lists the Changes to Bricolage introduced with each release.

=head1 Version 1.2.4

=head2 Bug Fixes

=over 4

=item *

Fixed Bric::Util::FTP::FileHandle to create new revisions on PUT.  [Sam]

=item *

Deleting a contributor will no longer break stories with which the contributor
is associated. Thanks to Rachel Murray for the spot. [David]

=item *

Invalid configuration directives in bricolage.conf will now be caught and keep
Bricolage from starting. [Sam]

=item *

The view button in the element profile now works correctly. Thanks to Joao Pedro
Goncalves for the spot. [David]

=item *

Changed all strttime instances of '%G' to '%Y', as this seems to be
more portable. [David]

=back

=head1 Version 1.2.3

Functionally equivalent to 1.2.2, but includes required files missing from the
1.2.2 distribution.

=head1 Version 1.2.2

=head2 New Features

=over 4

=item *

Added chk_syntax() methods to Bric::Util::Burner and its subclasses. This method
will takes a tempmlate asset object and make sure that it compiles.
Bric::Util::Burner::chk_syntax() delegates to the proper subclass.

=back

=head2 Bug Fixes

=over 4

=item *

Some misspellings were corrected in Bric::Admin. Thanks to Ask Bjoern Hansen for
the spot. [David]

=item *

Fixed broken "Return" buttons on related media and related story pages. [David]

=item *

Fixed bug where assets weren't activated when they were creaed and then checked
in without clicking the "Save" button. [David]

=item *

Fixed bug where a fixed story's slug was getting used in its URI. [David]

=item *

Fixed broken image autopopulation fields (compression, height, width, etc.)
[David]

=item *

Fixed broken support for audio and video files. These can be set up by the Media
Type menu in Element Types. Eventually these should arrange for some fields to
be auto-populated (e.g., bit rate, frame size, length, encoding, etc.).

=item *

Fixed bug where Categories with the same directory name could not be created.
Thanks to Andrew Baio for the spot. [David]

=item *

Fixed a bug where a user couldn't look at her own event log if she didn't have
permission. Thank to Michael Alan Dorman for the spot. [David]

=item *

Fixed a bug where permissions set to access workflows and desks had no affect on
the display of workflows and desks. Thanks to Rachel Murray for the spot.
[David]

=item *

Fixed bug where attempting to create a destination with the same name as an
existing but deactivated destination triggered an SQL error. Thanks to Michael
Alan Dorman for the spot. [David]

=item *

Fixed bug where Workflows with spaces in their names would not create proper
submenus in the left navigation bar. Thanks to the WHO for the spot [David]

=item *

Fixed bug where the wrong story might be previewed when clicking the title of a
story in My Workspace or on a desk. [David]

=item *

Changing the category a media asset is in now correctly updates the underlying
category object and the URI without the media asset needing to be checked in.
[Matt Vella]

=item *

Eliminated "Template compile failed" errors for templates with <%init> sections.
[David]

=item *

Field elements now show up with their display names in the bulk edit select
lists, instead of with their names (which are really keys). [David]

=item *

Eliminated "Use of uninitialized value in bitwise or (|)" warnings when checking
permissions. Thanks to Sam Tregar for the spot. [David]

=item *

Custom fields in elements and contributor types now remember their "size"
setting. Thanks to Sam Tregar for the spot. [David]

=item *

The Element select list on the new Template profile no longer lists media
elements, since media assets don't use templates. [David]

=item *

Removed old XML::Writer stuff from Bric::Util::Burner, since I moved it to
Bric::Util::Burner::Mason a while ago and it was causing some problems. Thanks
to Michael Robinton for the spot. [David]

=item *

Fixed typo in Bric::Hacker spotted by Axel Beckert. [Sam]

=item *

The CREATE permission works properly now. Thanks to Rachel Murray for the spot.
[David]

=back

=head1 VERSION 1.2.1

=head2 New Features

=over 4

=item *

Created new method of configuring Bricolage in Apache. For mod_perl 1.26 and
earlier, a custom config file will be written to the bricolage temp directory
every time Bricolage is started or restarted. For mod_perl 1.27 and later, no
temp file will be written. [David]

=item *

Added support for Mozilla (and there was much rejoicing!). [David]

=item *

Changed password for the default "admin" user to "change me now!" [David]

=item *

The slug is stored in the database for both fixed and non-fixed stories. This is
in anticipation of adding the ability to use the slug for fixed story URIs later
on. Thanks to Darren Graves for the patch.

=item *

Added DISABLE_NAV_LAYER directive. It's off by default, but if you turn it on in
bricolage.conf, the side navigation layer will be rendered as plain HTML in
every page instead of as a separate layer. [David]

=item *

Documented PERL_LOADER directive in Bric::AdvTemplates. [David]

=back

=head2 Bug Fixes

=over 4

=item *

Turned off the PREVIW_MASON configuration directive in bricolage.conf. It should
be off by default. [David]

=item *

Deleted Output Channels now properly don't show up in the Output Channel manager
again. Thanks to Sara for the spot! [David]

=item *

All previews now preview assets in the primary Output Channel only. Previously,
the previews were in the Output Channel whose name came first alphabetically.
Thanks to Sara Wood for catching this bug. [David]

=item *

Fixed bug where templates often couldn't be found by the Mason burner if the
output channel had a post_path. [David]

=item *

Fixed bug where templates often couldn't be found by the HTML::Template burner
if the output channel had a post_path. [Sam]

=item *

Fixed some problems with the sideNav menus under Netscape. [David]

=item *

Fixed broken "Preview" button in Read-only story profile and in related story
elements. [Matt Vella]

=item
way to grab media files for editing and such, as it will not incur the overhead
of distributing the media file. [David]

=item *

Allow only one template with a given name for a given category, element, burner
and output channel. [Sam]

=item *

Added a Maintainer section to the About page. [David]

=item *

Updated About page to mimic the layout of the help pages. [David]

=back

=head2 Bug Fixes

=over 4

=item *

Fixed a bug with local previews where a preview page could show up instead of
the Bricoalge UI. Thanks to Sara for the spot. [David]

=item *

Fixed a bug where Mason component calls failed in previews when the
PREVIEW_MASON directive was enabled. [David]

=item *

Changed default value for text area fields added via the form builder (i.e., in
Contributor Type and Element profiles) to 0. The values 0 and "" always make the
the new field unlimited in length. [David]

=item *

Fixed a couple of buttons to be proper case rather than upper case. [David]

=item *

Separated the filesystem destinations for assets burned for publication and for
assets burned for previewing. This will prevent someone previewing and stomping
all over a published version of an asset before the published version is
distributed. [David]

=item *

Removed hard-coding of the local preview directory in httpd.conf and
httpd-ssl.conf. Now using the values stored in PREVIEW_LOCAL, instead, to
determine the proper directory. [David]

=item *

Added the DEF_MEDIA_TYPE directive. Bricolage will use the value in this
directive to assign a Media Type to all file resources if they Bricolage can't
figure it out from their file extentions. This fixes a bug where Bricolage would
choke if it couldn't figure out the MediaType itself. [David]

=back

=head1 VERSION 1.0.2

=head2 New Features

=over 4

=item *

Added "File Name" and "File Extension" properties to OutputChannels. These
properties will now be used to name files burned to the file system on
preview and publish. [David]

=item *

Added DEFAULT_FILENAME and DEFAULT_FILE_EXT configuration directives to set
default values on the "File Name" and "File Extenstion" Output Channel
properties. [David]

=item *

Changed Bric::Util::Burner->display_element() so that it doesn't paginate. All
paginated pages are now treated instead as regular elements. This is useful for
things like printer-freindly pages. Bric::Util::Burner->display_element()
contines to work as before. Use this method to output a separate file for each
paginated element. [David]

=item *

When errors occur while previewing stories, the leftNav is now turned off.
[David]

=item *

Browser buttons and menus are now disabled. [David]

=item *

Added ability to set permissions on assets based on the categories they're in.
[David]

=item *

Moved all session and session locking files into the "bricolage" subdirectory of
the local file system's tmp directory. You'll want to rm -rf /tmp/bricolage_*
upon upgrading. [David]

=item *

Moved the location of cache files to the "bricolage/cache" subdirectory of the
local file system's tmp directory. You'll want to rm -rf /tmp/FileCache upon
upgrading. Together with the above change, this means that all Bricolage
temporary files are stored in the "bricolage" subdirectory of the local tmp,
e.g., /tmp/bricolage. [David]

=item *

Added new program, bric_clean_tmp, that can be used in a cron job to delete
stale temporary files. [Sam]

=item *

Added an "About" page, linked from the logo graphic, that explains the name
"Bricolage" and offers the license and credits. [David]

=item *

Added PERL_LOADER configuration directive. Pass a line of Perl to this
directive, and on startup, it'll execute it in the same namespace as your
templates execute in. [David]

=item *

Added INCLUDE_XML_WRITER and XML_WRITER_ARGS configuration parameters. If
INCLUDE_XML_WRITER is turned on, then all templates will include a new global,
$writer, that is an XML::Writer object. This object is provided as a convenience
for creating XML in your templates. XML_WRITER_ARGS allows certain arguments to
be passed to the XML::Writer i

Fixed bug where data fields deleted from Elements were deleting them from
existing stories, too. [David]

=item *

Fixed bug where stories with related media associated with them were displaying
the story as an Element rather than as a story after editing the related media.
[David]

=item *

Removed all file system location dependencies for the operation of Bricolage.
Bricolage will still assume that everything's in /usr/local/bricolage, but any
location is fine as long as the BRICOLAGE_ROOT environment variable is set to
the proper location. [David]

=item *

Added code to force all preview pages to be re-requested from the server every
time they're viewed. This prevents the browser from loading older versions from
its cache, and allows users to always see the most recently-burned output of a
story. [David]

=item *

Removed debugging information from URLs for when debugging is turned off --
which should be always in production code (e.g., releases). [David]

=item *

Elements are now displayed with their display names rather than their attribute
names. Thanks to Sam Tregar for the spot. [David]

=item *

Fixed bug where fields (attributes) added to an Element with the name of an
existing but deactivated field triggered an error. Thanks to Sam for the
heads-up. [David]

=item *

Fixed a bug where data fields sometimes were not propery retreived from the
database in Bric::Biz::AssetType. [David]

=item *

Fixed a bug where clicking "Save and Stay" in the Element profile wouldn't
delete attributes (fields) marked as such, or even delete the Element itself, if
the "Delete this profile" checkbox was checked.

=item *

Fixed a bug where, for Story and Media assets, editors were given Edit access to
notes, even when they didn't have the asset checked out. [David]

=item *

Changed the misleading and inaccurate "Two blank lines" label in the Bulk Edit
interface to the more accurate "One blank line". Thanks to Sam Tregar for the
heads-up.

=back

=head1 VERSION 1.0.1

=over 4

=item *

Initial public release.

=back

=head1 AUTHOR

David Wheeler <david@wheeler.net>

=head1 SEE ALSO

L<Bric|Bric>

=cut
