=head1 NAME

Bric::FAQ - Bricolage Frequently Asked Questions

=head1 VERSION

$Revision: 1.7.2.1 $

=head1 DATE

$Date: 2003-03-19 00:43:57 $

=head1 DESCRIPTION

This document tries to answer questions asked frequently
on the mailing list or other questions that people might
have when starting out with or evaluating Bricolage.

=head1 FAQs

=head2 Evaluating Bricolage

This section answers questions that someone evaluating
Bricolage might have.

=head3 Does Bricolage support databases other than PostgreSQL?

Currently only PostgreSQL support is maintained. There is
an Oracle driver, but it's old and not known to work. David
says there is also a MySQL driver somewhere, though I don't
see it in the sources.

Many people have asked whether Bricolage will support
MySQL. The problem used to be that MySQL didn't support
transactions; now it can, but there is no support in
Bricolage for it yet. Patches are welcome.

=head3 How well does Bricolage perform?

I dunno. [compare to mod_perl, CGI, static, other CMSs ... ?]

=head3 How does Bricolage compare to other content management systems?

It has received praise for being as good as or better than commercial
alternatives. For example, see
L<http:E<sol>E<sol>www.eweek.comE<sol>article2E<sol>0,3959,652977,00.asp>

=head3 Who uses Bricolage?

Some that we know of are:

=over 4

=item *

The PIRT Group - L<http:E<sol>E<sol>thepirtgroup.comE<sol>>

=item *

World Health Organization - L<http:E<sol>E<sol>www.who.intE<sol>>

=item *

DFA - L<http:E<sol>E<sol>dfafunds.comE<sol>>

=item *

Macworld - L<http:E<sol>E<sol>www.macworld.comE<sol>>

=item *

Ad Council - L<http:E<sol>E<sol>www.adcouncil.orgE<sol>>

=back

=head2 Installation

=head3 Why does mod_perl have to be statically compiled into Apache? I've been
using mod_perl as a DSO and have had no problems with it at all.

You are very fortunate, because mod_perl 1.x is just not too stable as a
DSO. Weird things tend to happen. That's not to say that some haven't set it
up as a DSO and just had it work, but we've seen all sorts of unexplainable
problems just evaporate when users have switched from a DSO to a static
mod_perl. And it's not Bricolage so much as Mason where the problems are
noticed. The Mason site (L<http:E<sol>E<sol>www.masonhq.comE<sol>>) has a
couple of FAQs that mention the issue:

=over 4

=item *

L<http:E<sol>E<sol>www.masonhq.comE<sol>docsE<sol>faqE<sol>#why_am_i_getting_segmentation_fa>

=item *

L<http:E<sol>E<sol>www.masonhq.comE<sol>docsE<sol>faqE<sol>#does_mason_leak_memory>

=back

You can also search the Mason Users list archives
(L<http:E<sol>E<sol>marc.theaimsgroup.comE<sol>?l=mason>) and the mod_perl
Users list
archives (L<http:E<sol>E<sol>marc.theaimsgroup.comE<sol>?l=apache-modperl>) for some
discussions of this issue.

=head2 Error Messages

This section contains questions about error messages output
by Bricolage.

=head3 Why does C<make install> exit with the following error?

    Missing or empty inst/bricolage.sql!

You downloaded Bricolage from CVS and didn't
run `make dist`. Do something like this:

    # make dist
    [lots of output...]
    # cd bricolage-1.5.0
    # make install

=head3 Why do I get an error like the following in Apache's F<error_log>?

    [error] access to / failed for 127.0.0.1, reason: No cookies found.

This only happens the first time your browser accesses Bricolage.
It is harmless and indicates that no Bricolage session cookie
has been set yet.

=head3 Why do I get a 404 when I connect to the Bricolage UI and get an
error like the following in Apache's F<error_log>?

  [error] [client 127.0.0.1] Error executing AccessHandler: Bric::App::Session -- /usr/local/lib/perl5/site_perl/5.8.0/Bric/App/Session.pm -- 236
  Difficulties tie'ing the session hash to file '/tmp/bricolage/session'

Most likely it is because one or more files or directories in your Bricolage
temp directory are no longer writable by the Apache user. You need to C<chown>
the temp file directories and restart Bricolage:

  sudo chown -R nobody:nobody /tmp/bricolage
  sudo bric_apachectl restart

=head3 When I try to login to Bricolage, I get redirected to F</login>, but
the page is blank. There's nothing in the HTML source except C<<
<html><head></head></html> >> or nothing at all. There are no errors in the
error log or the access log. What's wrong?

I've seen this a couple of times, but the cause was different each time. On
one occasion, there was a F<FilesMatch> directive in a separate VirtualHost
directive in F<httpd.conf> that was preventing Mason from seeing any of the
Bricolage UI components. The directive that caused the problem looked like
this:

  <FilesMatch "\.mas">
    SetHandler  perl-script
    PerlHandler Bric::App::Handler
  </FilesMatch>

I have no idea why this would have caused a problem, but when it was removed,
Bricolage started working again.

On another occasion, a user noticed that the files F<comp/login/dhandler> and
F<comp/login/welcome.html> were empty. This caused the equivalent of a
"Document Contains No Data" error, only it didn't. In fact, in my tests, under
these circumstances, the browser had no HTML source at all (although I was
later told that a Mozilla setting can force the C<< <html><head></head></html>
>> to be added). At any rate, the problem was fixed by reinstalling Bricolage
(a C<make upgrade> would probably do the trick, too), but it's likely that
simply copying these two files from the Bricolage source directories to your
installed component root will correct the problem. Holler on the
bricolage-general mail list if it doesn't.

=head2 Element Administration

=head3 I added a field to an element and deleted it, and now I can't add a new
field with the same name. Why not?

Fields cannot have the same name, even if they've been deleted. This is
because you might have older stories around that use the old name, and still
republish them to templates that use the old name.

The solution is to give the new version of the field a different name, but
make the "Label" the same. So you might have a name like "new_paragraph" and
the label "Paragraph". Just remember to change any references to the old field
name in your templates to use the new field name.

=head2 Miscellaneous

This section contains questions that didn't fit in the other
sections.

=head3 What does "Bricolage" mean?

See the "About" section of the online help.

=head3 How did Bricolage get started? What is its history?

[In the beginning there was chaos....]

=head3 Where can I get more information?

Read the F<README> document in the directory where you unpacked Bricolage to
learn about other documents on specific things like Bricolage administration,
usage, or hacking. The project's website is
L<http:E<sol>E<sol>www.bricolage.ccE<sol>>. The
website lists information about mailing lists.

=head1 AUTHOR

Scott Lanning <slanning@theworld.com>

=head1 SEE ALSO

F<README>,
L<http:E<sol>E<sol>bricolage.ccE<sol>>,
L<Bric::Admin|Bric::Admin>

=cut
