=head1 NAME

Bric::FAQ - Bricolage Frequently Asked Questions

=head1 VERSION

$Revision: 1.5 $

=head1 DATE

$Date: 2003-02-19 18:56:45 $

=head1 DESCRIPTION

This document tries to answer questions asked frequently
on the mailing list or other questions that people might
have when starting out with or evaluating Bricolage.

=head1 FAQs

=head2 Evaluating Bricolage

This section answers questions that someone evaluating
Bricolage might have.

=head3 Does Bricolage support databases other than PostgreSQL?

Currently only PostgreSQL support is maintained. There is
an Oracle driver, but it's old and not known to work. David
says there is also a MySQL driver somewhere, though I don't
see it in the sources.

Many people have asked whether Bricolage will support
MySQL. The problem used to be that MySQL didn't support
transactions; now it can, but there is no support in
Bricolage for it yet. Patches are welcome.

=head3 How well does Bricolage perform?

I dunno. [compare to mod_perl, CGI, static, other CMSs ... ?]

=head3 How does Bricolage compare to other content management systems?

It has received praise for being as good as or better than commercial
alternatives. For example, see
L<http://www.eweek.com/article2/0,3959,652977,00.asp>

=head3 Who uses Bricolage?

Some that we know of are:

=over 4

=item *

The PIRT Group - L<http://thepirtgroup.com/>

=item *

World Health Organization - L<http://www.who.int/>

=item *

DFA - L<http://dfafunds.com/>

=item *

Macworld - L<http://www.macworld.com/>

=item *

Ad Council - L<http://www.adcouncil.org/>

=back

=head2 Installation

=head3 Why does mod_perl have to be statically compiled into Apache? I've been
using mod_perl as a DSO and have had no problems with it at all.

You are very fortunate, because mod_perl 1.x is just not too stable as a
DSO. Weird things tend to happen. That's not to say that some haven't set it
up as a DSO and just had it work, but we've seen all sorts of unexplainable
problems just evaporate when users have switched from a DSO to a static
mod_perl. And it's not Bricolage so much as Mason where the problems are
noticed. The Mason site (L<http://www.masonhq.com/>) has a couple of FAQs that
mention the issue:

=over 4

=item *

L<http://www.masonhq.com/docs/faq/#why_am_i_getting_segmentation_fa>

=item *

L<http://www.masonhq.com/docs/faq/#does_mason_leak_memory>

=back

You can also search the Mason Users list archives
(L<http://marc.theaimsgroup.com/?l=mason>) and the mod_perl Users list
archives (L<http://marc.theaimsgroup.com/?l=apache-modperl>) for some
discussions of this issue.

=head2 Error Messages

This section contains questions about error messages output
by Bricolage.

=head3 Why does C<make install> exit with the following error?

    Missing or empty inst/bricolage.sql!

You downloaded Bricolage from CVS and didn't
run `make dist`. Do something like this:

    # make dist
    [lots of output...]
    # cd bricolage-1.5.0
    # make install

=head3 Why do I get an error like the following in Apache's F<error_log>?

    [error] access to / failed for 127.0.0.1, reason: No cookies found.

This only happens the first time your browser accesses Bricolage.
It is harmless and indicates that no Bricolage session cookie
has been set yet.

=head2 Element Administration

=head3 I added a field to an element and deleted it, and now I can't add a new
field with the same name. Why not?

Fields cannot have the same name, even if they've been deleted. This is
because you might have older stories around that use the old name, and still
republish them to templates that use the old name.

The solution is to give the new version of the field a different name, but
make the "Label" the same. So you might have a name like "new_paragraph" and
the label "Paragraph". Just remember to change any references to the old field
name in your templates to use the new field name.

=head2 Miscellaneous

This section contains questions that didn't fit in the other
sections.

=head3 What does "Bricolage" mean?

See the "About" section of the online help.

=head3 How did Bricolage get started? What is its history?

[In the beginning there was chaos....]

=head3 Where can I get more information?

Read the F<README> document in the directory where you unpacked Bricolage to
learn about other documents on specific things like Bricolage administration,
usage, or hacking. The project's website is L<http://www.bricolage.cc/>. The
website lists information about mailing lists.

=head1 AUTHOR

Scott Lanning <slanning@theworld.com>

=head1 SEE ALSO

F<README>,
L<http://bricolage.cc/>,
L<Bric::Admin|Bric::Admin>

=cut
