=head1 Name

Bric::Hacker - A guide for Bricolage hackers.

This document has been moved to the Bricolage Wiki,
L<http://wiki.github.com/bricoleurs/bricolage>. Relevant documents include:

=over

=item * L<http://wiki.github.com/bricoleurs/bricolage/community>

=item * L<http://wiki.github.com/bricoleurs/bricolage/coding-standards>

=item * L<http://wiki.github.com/bricoleurs/bricolage/working-with-git>

=item * L<http://wiki.github.com/bricoleurs/bricolage/contributing-a-bug-fix>

=item * L<http://wiki.github.com/bricoleurs/bricolage/working-with-branches>

=item * L<http://wiki.github.com/bricoleurs/bricolage/contributing-via-email>

=item * L<http://wiki.github.com/bricoleurs/bricolage/contributing-actions-and-movers>

=item * L<http://wiki.github.com/bricoleurs/bricolage/debugging>

=item * L<http://wiki.github.com/bricoleurs/bricolage/merging-with-git>

=item * L<http://wiki.github.com/bricoleurs/bricolage/starting-a-project-branch>

=item * L<http://wiki.github.com/bricoleurs/bricolage/creating-a-release>

=item * L<http://wiki.github.com/bricoleurs/bricolage/git-hacks>

=item * L<http://wiki.github.com/bricoleurs/bricolage/performance-tuning>

=back
