=head1 Name

Bric::Hacker - A guide for Bricolage hackers.

This document has been moved to the L<Bricolage
Wiki|http://wiki.github.com/bricoleurs/bricolage>. Relevant documents include:

=over

=item * L<Community|http://wiki.github.com/bricoleurs/bricolage/community>

=item * L<Coding Standards|http://wiki.github.com/bricoleurs/bricolage/coding-standards>

=item * L<Working with Git|http://wiki.github.com/bricoleurs/bricolage/working-with-git>

=item * L<Contributing a Bug Fix|http://wiki.github.com/bricoleurs/bricolage/contributing-a-bug-fix>

=item * L<Working with Branches|http://wiki.github.com/bricoleurs/bricolage/working-with-branches>

=item * L<Contributing Via Email|http://wiki.github.com/bricoleurs/bricolage/contributing-via-email>

=item * L<Contributing Actions and Movers|http://wiki.github.com/bricoleurs/bricolage/contributing-actions-and-movers>

=item * L<Debugging|http://wiki.github.com/bricoleurs/bricolage/debugging>

=item * L<Merging with Git|http://wiki.github.com/bricoleurs/bricolage/merging-with-git>

=item * L<Starting a Project Branch|http://wiki.github.com/bricoleurs/bricolage/starting-a-project-branch>

=item * L<Creating a Release|http://wiki.github.com/bricoleurs/bricolage/creating-a-release>

=item * L<Git Hacks|http://wiki.github.com/bricoleurs/bricolage/git-hacks>

=item * L<Performance Tuning|http://wiki.github.com/bricoleurs/bricolage/performance-tuning>

=back
