=head1 Name

Bric::License - The Bricolage License.

=head1 Copyright and License

Copyright (c) 2001-2002. About.com. Changes Copyright (c) 2002-2009
Kineticode, Inc. and others.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

=over

=item *

Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

=item *

Redistributions in binary form must reproduce the above copyright notice, this
list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

=item *

Neither the name of the About.com nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

=back

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


=head2 Icons

Some of the icons included by Bricolage are covered under other open source
licenses:

=over

=item * 

The Nuvola icon set, from David Vignoni (L<http://icon-king.com>), is covered
under the GNU Lesser General Public License:

=over

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

=back

=item *

The Tango icon set, from the Tango Desktop Project 
(L<http://tango.freedesktop.org>), is covered under the 
Creative Commons Attribution Share-Alike license: 
L<http://creativecommons.org/licenses/by-sa/2.5/>

=back


=head1 Credits

Bricolage is maintained by:

=over

=item * David Wheeler <david@kineticode.com>

=back

The current development team consists of:

=over

=item * David Wheeler <david@kineticode.com>

=item * Scott Lanning <lannings@who.int>

=item * Marshall Roch <marshall@exclupen.com>

=back

The original developers were:

=over

=item * David Wheeler <david@kineticode.com>

=item * Garth Webb <garth@perijove.com>

=item * Michael Soderstrom <miraso@pacbell.net>

=item * David Gantenbein <fretlessbass@attbi.com>

=back

Emeritus Developers:

=over

=item * Garth Webb <garth@perijove.com>

=item * Michael Soderstrom <miraso@pacbell.net>

=item * David Gantenbein <fretlessbass@attbi.com>

=item * Sam Tregar <sam@stregar.com>

=item * Mark Jaroski <mark@geekhive.net>

=back

The user interface was designed by:

=over

=item * Kristee Rosendahl

=back

With later enhancements by:

=over

=item * David Wheeler

=item * Marshall Roch

=back

The online help was written by:

=over

=item * Chris Brody <chris_brody@hotmail.com>

=item * David Wheeler <david@kineticode.com>

=item * Geoff Richards <geoffr@gbdirect.co.uk>

=back

Folks who have submitted patches include:

=over

=item * Sam Tregar

=item * JoE<atilde>o Pedro GonE<ccedil>alves

=item * Rachel Murray

=item * Matt Vella

=item * Jeff "japhy" Pinyan

=item * Adam Robinson

=item * Darren Graves

=item * Mike Slattery

=item * Andrew Baio

=item * Charles Albrecht

=item * Michael Robinton

=item * Petar Bojkov

=item * Neil Conway

=item * Geoff Richards

=item * ClE<aacute>udio Valente

=item * Eldar Kononov

=item * Kevin White

=item * Kang-min Liu

=item * Clive Jones

=item * Cinly Ooi

=item * Radu Greab

=item * Thorsten Biel

=item * Dave Rolsky

=item * Simon Wilcox

=item * Nate Perry-Thistle

=item * Josh Berkus

=item * Simon Myers

=item * Serge Sozonoff

=item * Paul Orrock

=item * Florian Rossol

=item * Eric Sellers

=item * Rod Taylor

=item * Cameron Miller

=item * Andrea Rota

=item * Mark Kennedy

=item * Keith Grennan

=item * Christian Hauser

=item * Dharmender Yadav

=item * Benjamin Franz

=item * Alexey Sheynuk

=item * Christian Muise

=item * Christian Niles

=item * Brad Harder

=item * Brad Fox

=item * Alexey Dvoychenkov

=item * Alex Howarth

=item * David Beaudet

=item * Steffen Schwigon

=item * Bret Dawson

=item * Rolf Schaufelberger

=item * Greg Heo

=item * Phillip Smith

=item * Alex Krohn

=item * Brian Smith

=item * Adrian Yee

=item * Matt Rolf

=item * Sarah Mercier

=item * Michael Herring

=item * Kahil Jallad

=item * Michael MartE<iacute>

=back

Friends who have spotted bugs include:

=over

=item * Michael Alan Dorman

=item * Josh Cox

=item * Marlon Bermas

=item * Tracey Largay

=item * Ask BjE<oslash>rn Hansen

=item * Daniel Fisher

=item * Philip Fibiger

=item * Evan Prodromou

=item * John Greene

=item * Sean Greathouse

=item * Shannon Brown

=item * Bill Cappel

=item * Todd Tyree

=item * Ilia Chipitsine

=item * Alex Epshteyn

=item * Alex Wheeler

=item * Chris Jantzen

=item * Paul Cory

=item * Jeff Steele

=item * Lari Huttunen

=item * Nathan Ollerenshaw

=item * Marc Hawson

=item * Tobias Kremer

=item * Kevin Elliott

=item * Michael G. Kaiser

=item * Radu Greab

=item * Rudy Lippan

=item * Perrin Harkins

=item * Chris Riddoch

=item * Gary Gilchrist

=item * Creighton Higgins

=item * Earle Martin

=item * Alexander Ling

=item * Adeola Awoyemi

=item * Neal Sofge

=item * Patrick Walsh

=item * Ben Bangert

=item * Ho Yin Au

=item * Abdul Halim Mazahar

=item * Tony Cowderoy

=item * Joshua Edelstein

=item * Will Trillich

=item * Adam Rinehart

=item * Hal Creech

=item * Patrick Michael Kane

=item * Kenneth Marshall

=item * Clinton Gormley

=item * Ed Stevenson

=item * Ashlee Caul

=item * Clare Parkinson

=item * Jason Edgecombe

=item * Frank Holtz

=item * Martin Bacovsky

=item * Curtis Poe

=item * JosE<eacute> Castro

=item * Alexandra Gershman

=item * Guido BE<uuml>lskE<auml>mper

=item * Wayne Slavin

=item * Jerry Franz

=item * Paul Hyland

=item * Frank Febbraro

=item * Li Li

=item * Michael Holden

=item * Michael Cummings

=item * Derek Poon

=item * Ryan O'Toole

=item * Tom Kjeldsen

=item * George Harrison

=item * John Gillis

=item * Chris Sutton

=item * Doug Dawson

=item * Chris Heiland

=item * Michael Glaesemann

=item * Joe Pletcher

=item * Andrei Arsu

=item * Chris Schults

=item * Dan McGarry

=item * Daisuke Maki

=item * Dawn Buie

=item * Ryan O'Toole

=item * Chauncey Thorn

=item * Matt Wlazlo

=item * Jean-Michel Caricand

=item * Tatiana Titova

=item * John Watson

=item * Ed Guzman

=item * John Kirkwood

=item * Roland van Ipenburg

=item * Denny de la Haye

=item * Krzysztof Rudnik

=item * Adam Wilson

=back

Bricolage's translation team:

=over

=item * ClE<aacute>udio Valente and Pedro Custodio (Portuguese)

=item * Marco Ghezzi (Italian)

=item * Kang-min Liu (Traditional Chinese)

=item * Gerfried Fuchs, Thorsten Biel, Florian Rossol, and Steffen Schwigon (German)

=item * Gang Luo (Simplified Chinese)

=item * Sergey Samoilenko (Russian)

=back

Others who contributed to its support and development:

=over

=item * Sara Plath

=item * Sara Wood

=item * Chad Dickerson

=item * Jason Merrick

=item * Tim Taschler

=item * John Allspaw

=item * Matt Lanier

=item * Joseph Fajen

=item * Lisa Ratner

=item * Ian Kallen

=item * Michele Jenkins

=item * Elizabeth Kairys

=back

=cut

